### GET request with a header
### Get all posts

GET http://localhost:5000/posts
Accept: application/json


### Send POST request with json body
POST http://localhost:5000/posts
Content-Type: application/json

{
  "title": "Третій тестовий заголовок до допису номер 3",
  "subtitle": "Третій тестовий підзаголовок до допису нормер 3",
  "text": "Текст до мого другого тестового допису, зараз і подивлюсь як це працює! І ще до добавлю багато тексту, щоб подивитсь як це прцює, тому я готвий добавати цей допис в базу даних та подивитись на нього вже зі сторони фронтенду. Текст до мого другого тестового допису, зараз і подивлюсь як це працює! І ще до добавлю багато тексту, щоб подивитсь як це прцює, тому я готвий добавати цей допис в базу даних та подивитись на нього вже зі сторони фронтенду.",
  "tags": ["posts", "test", "words", "awesome", "programming", "рекомендації", "теги", "тест", "допис", "posts", "test", "words", "awesome", "programming", "рекомендації", "теги", "тест", "допис"],
  "category": "Бізнес",
  "likes_count": 1782,
  "views_count": 17034
}